In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)
a=np.arange(10)
print(a)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
%timeit [i**2 for i in range(1000)]

183 µs ± 993 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

1.21 µs ± 9.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Array

In [8]:
# 1-D
a=np.array([1,2,3,4,5,6])

print("a.ndim : ",a.ndim)

print("a.shape : ",a.shape)

print("len(a) : ",len(a))

a.ndim :  1
a.shape :  (6,)
len(a) :  6


In [13]:
#2-D
b=np.array([[1,2,3],[6,7,8]])
print("b: \n",b)
print("Shape: ",b.shape)
print("ndim: ",b.ndim)
print("len: ",len(b))

b: 
 [[1 2 3]
 [6 7 8]]
Shape:  (2, 3)
ndim:  2
len:  2


### creation of numpy array using arrange(), linspace(), ones(), zeros(), eye(), diag(), rand()

In [25]:
a=np.arange(1,18,2)
print(a)

a=np.linspace(1,20,30)
print(a)
print(a.shape)

[ 1  3  5  7  9 11 13 15 17]
[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207
  4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655
  8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103
 12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552
 16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]
(30,)


In [63]:
b=np.ones((1,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [30]:
c=np.zeros((4,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
d=np.eye(4,5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


diag() is used to create matrix whose diagonal elements are known and other are zero

and also disag() extracts diagonal element as a array from matrix

In [34]:
e=[1,2,3,4,5]
f=np.diag(e)
print(f)
print(type(f),f.shape)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
<class 'numpy.ndarray'> (5, 5)


In [36]:
g=np.diag(f)
print(g)
print(type(g),g.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'> (5,)


### np.random.rand()  np.random.randn() np.random.randint()

In [37]:
a=np.random.rand(4)
print(a)

[0.78004301 0.01438545 0.97745359 0.51687595]


In [39]:
b=np.random.randn(5)
print(b)

[ 0.76049435 -0.61498004  1.88216485  1.28640505  0.99927421]


### dtype

In [40]:
a=np.arange(10)
a.dtype

dtype('int64')

In [42]:
a=np.arange(10,dtype='float64')
print(a)
a.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [45]:
k=[0 for i in range(15)]
k=np.array(k)
k[2:13:2]=33
print(k)

[ 0  0 33  0 33  0 33  0 33  0 33  0 33  0  0]


### Fancy Indexing
Mask creates Copy 

slicing creates View

In [48]:
a=np.random.randint(0,20,15)
a

array([12, 15, 16,  1, 19,  5,  6, 12, 11, 11, 14, 18, 16,  7, 16])

In [50]:
mask=(a%2==0)
extract_from_a = a[mask]
print(extract_from_a)

[12 16  6 12 14 18 16 16]


In [51]:
a[mask]=-1
print(a)

[-1 15 -1  1 19  5 -1 -1 11 11 -1 -1 -1  7 -1]


In [53]:
b=list(filter(lambda x:(x!=-1),a))
print(b)

[15, 1, 19, 5, 11, 11, 7]


### indexing of Numpy Array using List

slicing through list doesn't share memory

In [55]:
a=np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [57]:
b=a[[1,2,3,7,6]]
print(b)

[20 30 40 80 70]


False

In [58]:
print(a)
a[[2,4,5]]=0
print(a)

[10 20 30 40 50 60 70 80 90]
[10 20  0 40  0  0 70 80 90]
