### Operations

In [8]:
%timeit import numpy as np

121 ns ± 6.04 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [10]:
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [11]:
a**2

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [74]:
c=np.random.randint(0,5,size=(4,4))
print("c  :\n",c,"\n*************************")
print("c*c :\n",c*c,"\n*************************")
print("c.dot(c) :\n",c.dot(c),"\n*************************")

c  :
 [[0 1 3 4]
 [0 2 3 1]
 [0 4 4 2]
 [2 4 2 0]] 
*************************
c*c :
 [[ 0  1  9 16]
 [ 0  4  9  1]
 [ 0 16 16  4]
 [ 4 16  4  0]] 
*************************
c.dot(c) :
 [[ 8 30 23  7]
 [ 2 20 20  8]
 [ 4 32 32 12]
 [ 0 18 26 16]] 
*************************


In [18]:
# Comparision
a=np.array([1,2,3,4])
b=np.array([4,2,3,1])
a==b

array([False,  True,  True, False])

In [20]:
c=np.array([1,2,3,4])
np.array_equal(c,a)

True

In [21]:
#logical operator
A=np.array([1,0,0,1])
B=np.array([1,1,0,0])
np.logical_or(A,B)

array([ True,  True, False,  True])

### Transcendental functions

In [22]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [23]:
np.log(a)

/home/saliakvihs/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [24]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Reductions

In [25]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [26]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
x.sum(axis=0)   #column first dimension

array([4, 6])

In [28]:
x.sum(axis=1)   #row first dimension

array([3, 7])

In [31]:
x.min()

1

In [32]:
x.min(axis=1)

array([1, 3])

### Logical \'or\' any()  and \'and\' all()

In [33]:
np.all(np.array([True,True,True,False]))

False

In [34]:
np.any(np.array([True,False,False,False]))

True

In [52]:
x=np.random.randint(0,20,(2,2))
print(x)
np.any(x==10)

[[ 4 10]
 [ 0 14]]


True

In [53]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
c=np.array([4,5,6,8])
((a<=b)&(b<=c)).all()

True

## Statistics

In [54]:
x=np.random.randint(5,20,15)
y=np.random.randint(5,20,(2,6))
print(x,y,sep='\n')

[16 15 18 18  5 12  5  7 16 16  8 16 15  9  6]
[[18 15 10  7 14  9]
 [14 16 19 18 19  6]]


In [55]:
x.mean()

12.133333333333333

In [56]:
y.mean(axis=1)

array([12.16666667, 15.33333333])

In [57]:
x.std()

4.745055906473132

In [60]:
data=np.loadtxt('populations.txt')

In [61]:
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [64]:
years, hares, lynxes, carrots = data.T

In [65]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [68]:
populations=data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [69]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [70]:
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [75]:
populations.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

### np.tile()

In [81]:
a=np.tile(np.array([10,20,30,40]),(3,1))
print(a)

[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


In [87]:
a=np.arange(10,23,4)
a

array([10, 14, 18, 22])

In [90]:
print(a[np.newaxis,:])
print(a[np.newaxis,np.newaxis,:,np.newaxis])

[[10 14 18 22]]
[[[[10]
   [14]
   [18]
   [22]]]]


In [91]:
# EXample
a=np.array([10,20,30,40])
a=a[:,np.newaxis]
b=np.array([1,2,3])
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


# Array Shape Manipulations

#### Flattening

In [93]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.ravel()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [98]:
b=a.T.ravel()
print(b)

[1 4 2 5 3 6]


In [99]:
b

array([1, 4, 2, 5, 3, 6])

In [101]:
print(b.reshape(3,2))

[[1 4]
 [2 5]
 [3 6]]


### Sorting

In [108]:
data

array([[ 1900.,  4000.,  7600., 36700.],
       [ 1901.,  6100., 11200., 38200.],
       [ 1902.,  7400., 14600., 38600.],
       [ 1903.,  8000., 16200., 39000.],
       [ 1904.,  8300., 18100., 39400.],
       [ 1905.,  8600., 19500., 39800.],
       [ 1906.,  9100., 20600., 40600.],
       [ 1907.,  9700., 21400., 40900.],
       [ 1908.,  9800., 22000., 41300.],
       [ 1909., 10100., 24700., 41500.],
       [ 1910., 12300., 25400., 41800.],
       [ 1911., 13000., 27100., 42100.],
       [ 1912., 15800., 30000., 42300.],
       [ 1913., 19000., 36300., 43300.],
       [ 1914., 19500., 40300., 43800.],
       [ 1915., 29700., 44500., 47200.],
       [ 1916., 35200., 46000., 52300.],
       [ 1917., 41700., 46800., 57000.],
       [ 1918., 45700., 47300., 70200.],
       [ 1919., 48200., 51100., 76600.],
       [ 1920., 48300., 59400., 77400.]])

In [109]:
print(np.sort(data,axis=1))

[[ 1900.  4000.  7600. 36700.]
 [ 1901.  6100. 11200. 38200.]
 [ 1902.  7400. 14600. 38600.]
 [ 1903.  8000. 16200. 39000.]
 [ 1904.  8300. 18100. 39400.]
 [ 1905.  8600. 19500. 39800.]
 [ 1906.  9100. 20600. 40600.]
 [ 1907.  9700. 21400. 40900.]
 [ 1908.  9800. 22000. 41300.]
 [ 1909. 10100. 24700. 41500.]
 [ 1910. 12300. 25400. 41800.]
 [ 1911. 13000. 27100. 42100.]
 [ 1912. 15800. 30000. 42300.]
 [ 1913. 19000. 36300. 43300.]
 [ 1914. 19500. 40300. 43800.]
 [ 1915. 29700. 44500. 47200.]
 [ 1916. 35200. 46000. 52300.]
 [ 1917. 41700. 46800. 57000.]
 [ 1918. 45700. 47300. 70200.]
 [ 1919. 48200. 51100. 76600.]
 [ 1920. 48300. 59400. 77400.]]


In [111]:
# fancy sort argsort
a=np.array([6 ,2 ,5 ,1])
j=np.argsort(a)
j

array([3, 1, 2, 0])

In [112]:
a[j]

array([1, 2, 5, 6])